apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../local-setup/local-dockercompose.yaml convert --profile all
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: victoria
  name: victoria
spec:
  ports:
    - name: "8428"
      port: 8428
      targetPort: 8428
  selector:
    io.kompose.service: victoria
